
package com.mycompany.tiendaropa;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alejandrosuarez
 */
public class frmRealizarCompra extends javax.swing.JPanel {

    /**
     * Creates new form frmRealizarCompra
     */
    public frmRealizarCompra() {
        initComponents();
         public frmRealizarCompra() {
        initComponents();
        this.tabledetalles.setModel(modelo);
        this.modelo.addColumn("NATIONALIDAD");
         this.modelo.addColumn("GENERO");
          this.modelo.addColumn("TALLA");
          this.modelo.addColumn("PRENDAS");
          this.modelo.addColumn("CANTIDAD");
          this.modelo.addColumn("TOTAL A PAGAR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel1 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbonacionalidad = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        botonh = new javax.swing.JRadioButton();
        botonm = new javax.swing.JRadioButton();
        jSeparator4 = new javax.swing.JSeparator();
        cbotallas = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        txtprenda = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        spcantidad = new javax.swing.JSpinner();
        jSeparator7 = new javax.swing.JSeparator();
        txtprecio = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jSeparator16 = new javax.swing.JSeparator();
        btngenerar = new javax.swing.JButton();
        jSeparator19 = new javax.swing.JSeparator();
        btnlimpiar = new javax.swing.JButton();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledetalles = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        btnlimpiartabla = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        btnquitar = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JSeparator();
        btnnetopagar = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        txtnetopagar = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(790, 32767));
        setPreferredSize(new java.awt.Dimension(790, 500));

        jPanel1.setBackground(new java.awt.Color(163, 172, 172));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));
        jPanel1.add(filler5);

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Realizar Compra");
        jPanel1.add(jLabel1);
        jPanel1.add(filler6);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Nacionalidad:");
        jPanel2.add(jLabel2);

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator8.setPreferredSize(new java.awt.Dimension(90, 10));
        jSeparator8.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jSeparator8);

        jLabel3.setText("Genero:");
        jPanel2.add(jLabel3);

        jSeparator9.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator9.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator9.setPreferredSize(new java.awt.Dimension(70, 10));
        jPanel2.add(jSeparator9);

        jLabel4.setText("Talla:");
        jPanel2.add(jLabel4);

        jSeparator10.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator10.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator10.setPreferredSize(new java.awt.Dimension(70, 10));
        jPanel2.add(jSeparator10);

        jLabel5.setText("Prenda:");
        jPanel2.add(jLabel5);

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator11.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator11.setPreferredSize(new java.awt.Dimension(25, 10));
        jPanel2.add(jSeparator11);

        jLabel6.setText("Cantidad:");
        jPanel2.add(jLabel6);

        jSeparator12.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator12.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator12.setPreferredSize(new java.awt.Dimension(25, 10));
        jPanel2.add(jSeparator12);

        jLabel7.setText("Precio:");
        jPanel2.add(jLabel7);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        cbonacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Mexicano", "Extranjero" }));
        cbonacionalidad.addActionListener(this::cbonacionalidadActionPerformed);
        jPanel3.add(cbonacionalidad);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel3.add(jSeparator3);

        buttonGroup1.add(botonh);
        botonh.setText("Hombre");
        botonh.addActionListener(this::botonhActionPerformed);
        jPanel3.add(botonh);

        buttonGroup1.add(botonm);
        botonm.setText("Mujer");
        botonm.addActionListener(this::botonmActionPerformed);
        jPanel3.add(botonm);

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator4.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel3.add(jSeparator4);

        cbotallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "S", "M", "L" }));
        jPanel3.add(cbotallas);

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator5.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel3.add(jSeparator5);

        txtprenda.setMaximumSize(new java.awt.Dimension(90, 2147483647));
        txtprenda.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel3.add(txtprenda);

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator6.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel3.add(jSeparator6);

        spcantidad.setPreferredSize(new java.awt.Dimension(70, 25));
        jPanel3.add(spcantidad);

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator7.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel3.add(jSeparator7);

        txtprecio.setMaximumSize(new java.awt.Dimension(90, 2147483647));
        txtprecio.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel3.add(txtprecio);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jSeparator16.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator16.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator16.setPreferredSize(new java.awt.Dimension(90, 10));
        jSeparator16.setVerifyInputWhenFocusTarget(false);
        jPanel6.add(jSeparator16);

        btngenerar.setText("Generar Compra");
        jPanel6.add(btngenerar);

        jSeparator19.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator19.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator19.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator19.setPreferredSize(new java.awt.Dimension(25, 10));
        jPanel6.add(jSeparator19);

        btnlimpiar.setText("Limpiar");
        jPanel6.add(btnlimpiar);

        jSeparator20.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator20.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator20.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator20.setPreferredSize(new java.awt.Dimension(25, 10));
        jPanel6.add(jSeparator20);

        jLabel11.setText("Total a Pagar:");
        jPanel6.add(jLabel11);

        txttotal.setActionCommand("<Not Set>");
        txttotal.setMaximumSize(new java.awt.Dimension(90, 2147483647));
        txttotal.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel6.add(txttotal);

        jPanel4.setBackground(new java.awt.Color(139, 150, 149));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jPanel4.add(filler4);

        jLabel8.setFont(new java.awt.Font("Adwaita Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Detalles de Compra");
        jLabel8.setAlignmentX(0.5F);
        jPanel4.add(jLabel8);

        jSeparator1.setBackground(new java.awt.Color(139, 150, 149));
        jSeparator1.setForeground(new java.awt.Color(139, 150, 149));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel4.add(jSeparator1);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(700, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(220, 200));

        tabledetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabledetalles.setMaximumSize(new java.awt.Dimension(700, 200));
        tabledetalles.setPreferredSize(new java.awt.Dimension(220, 200));
        jScrollPane1.setViewportView(tabledetalles);

        jPanel4.add(jScrollPane1);

        jSeparator2.setBackground(new java.awt.Color(139, 150, 149));
        jSeparator2.setForeground(new java.awt.Color(139, 150, 149));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel4.add(jSeparator2);

        jPanel5.setBackground(new java.awt.Color(139, 150, 149));
        jPanel5.setMaximumSize(new java.awt.Dimension(750, 100));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 25));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        btnlimpiartabla.setText("Limpiar Tabla");
        btnlimpiartabla.addActionListener(this::btnlimpiartablaActionPerformed);
        jPanel5.add(btnlimpiartabla);

        jSeparator13.setBackground(new java.awt.Color(139, 150, 149));
        jSeparator13.setForeground(new java.awt.Color(139, 150, 149));
        jSeparator13.setMaximumSize(new java.awt.Dimension(50, 3));
        jSeparator13.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel5.add(jSeparator13);

        btnquitar.setText("Quitar Compra");
        jPanel5.add(btnquitar);

        jSeparator14.setBackground(new java.awt.Color(139, 150, 149));
        jSeparator14.setForeground(new java.awt.Color(139, 150, 149));
        jSeparator14.setMaximumSize(new java.awt.Dimension(50, 3));
        jSeparator14.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel5.add(jSeparator14);

        btnnetopagar.setText("Total Neto a Pagar");
        jPanel5.add(btnnetopagar);

        jSeparator15.setBackground(new java.awt.Color(139, 150, 149));
        jSeparator15.setForeground(new java.awt.Color(139, 150, 149));
        jSeparator15.setMaximumSize(new java.awt.Dimension(50, 3));
        jSeparator15.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel5.add(jSeparator15);

        jLabel9.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Neto a Pagar: $");
        jPanel5.add(jLabel9);

        jSeparator17.setBackground(new java.awt.Color(139, 150, 149));
        jSeparator17.setForeground(new java.awt.Color(139, 150, 149));
        jSeparator17.setMaximumSize(new java.awt.Dimension(2, 3));
        jSeparator17.setPreferredSize(new java.awt.Dimension(2, 10));
        jPanel5.add(jSeparator17);

        txtnetopagar.setMaximumSize(new java.awt.Dimension(90, 50));
        jPanel5.add(txtnetopagar);

        jPanel4.add(jPanel5);
        jPanel4.add(filler2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modelo=new DefaultTableModel();
    // TODO add your handling code here:
     private void spcantidadActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    } 
     
      public void descuentos_hombres_mexicanos(){
     Double cantidad_s,precio_s,total_s,desc_s = 0.05;
        Double cantidad_m,precio_m,total_m,desc_m = 0.07;
        Double cantidad_l,precio_l,total_l,desc_l = 0.10;
        
        //Selecciona S
        if(cbonacionalidad.getSelectedIndex() == 2){
            if(this.botonh.isSelected()){
               if(cbotallas.getSelectedIndex() == 1){
                   cantidad_s = Double.parseDouble(this.spcantidad.getName());
                   precio_s = Double.parseDouble(this.txtprecio.getText());
                   total_s = (precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                   this.txttotal.setText(String.valueOf(total_s));
               } 
            }
            
        }
        
        //Selecciona M
        if(cbonacionalidad.getSelectedIndex() == 2){
            if(this.botonh.isSelected()){
               if(cbotallas.getSelectedIndex() == 2){
                   cantidad_m = Double.parseDouble(this.spcantidad.getName());
                   precio_m = Double.parseDouble(this.txtprecio.getText());
                   total_m = (precio_m*cantidad_m)-((cantidad_m*precio_m)*desc_m);
                   this.txttotal.setText(String.valueOf(total_m));
               } 
            }
            
        }
        //Selecciona L
        if(cbonacionalidad.getSelectedIndex() == 1){
            if(this.botonh.isSelected()){
               if(cbotallas.getSelectedIndex() ==3){
                   cantidad_l = Double.parseDouble(this.spcantidad.getName());
                   precio_l = Double.parseDouble(this.txtprecio.getText());
                   total_l = (precio_l*cantidad_l)-((cantidad_l*precio_l)*desc_l);
                   this.txttotal.setText(String.valueOf(total_l));
               } 
            } 
        }        
    }

    public void descuentos_hombre_extranjeros(){
       double cantidad_s,precio_s,total_s,desc_s=0.04;
       double cantidad_m,precio_m,total_m,desc_m=0.09;
       double cantidad_l,precio_l,total_l,desc_l=0.12;
       
       //Selecciona S
       if(cbonacionalidad.getSelectedIndex()==2){
          if(this.botonh.isSelected()){
            if(cbotallas.getSelectedIndex()==1){
                cantidad_s=Double.parseDouble(this.spcantidad.getName());
                 precio_s=Double.parseDouble(this.txtprecio.getText());
                  total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                  this.txttotal.setText(String.valueOf(total_s));
                  
            }
          }
       }
       //Selecciona M
      if (cbonacionalidad.getSelectedIndex()==2){
       if(this.botonh.isSelected()){
         if(cbotallas.getSelectedIndex()==2){
               cantidad_m=Double.parseDouble(this.spcantidad.getName());
                 precio_m=Double.parseDouble(this.txtprecio.getText());
                  total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m)*desc_m);
                  this.txttotal.setText(String.valueOf(total_m));
         }
       }
      }
      //Seleccionamos L
       if (cbonacionalidad.getSelectedIndex()==2){
       if(this.botonh.isSelected()){
         if(cbotallas.getSelectedIndex()==3){
               cantidad_l=Double.parseDouble(this.spcantidad.getName());
                 precio_l=Double.parseDouble(this.txtprecio.getText());
                  total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l)*desc_l);
                  this.txttotal.setText(String.valueOf(total_l));
            }
          }
       }
    }
    
    public void descuento_mujeres_extranjeras(){
        Double cantidad_s,precio_s,total_s,desc_s = 0.05;
        Double cantidad_m,precio_m,total_m,desc_m = 0.07;
        Double cantidad_l,precio_l,total_l,desc_l = 0.10;
        
        //Selecciona S
        if(cbonacionalidad.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
               if(cbotallas.getSelectedIndex() == 1){
                   cantidad_s = Double.parseDouble(this.spcantidad.getName());
                   precio_s = Double.parseDouble(this.txtprecio.getText());
                   total_s = (precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                   this.txttotal.setText(String.valueOf(total_s));
               } 
            }
            
        }
        
        //Selecciona M
        if(cbonacionalidad.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
               if(cbotallas.getSelectedIndex() == 2){
                   cantidad_m = Double.parseDouble(this.spcantidad.getName());
                   precio_m = Double.parseDouble(this.txtprecio.getText());
                   total_m = (precio_m*cantidad_m)-((cantidad_m*precio_m)*desc_m);
                   this.txttotal.setText(String.valueOf(total_m));
               } 
            }
            
        }
        //Selecciona L
        if(cbonacionalidad.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
               if(cbotallas.getSelectedIndex() == 3){
                   cantidad_l = Double.parseDouble(this.spcantidad.getName());
                   precio_l = Double.parseDouble(this.txtprecio.getText());
                   total_l = (precio_l*cantidad_l)-((cantidad_l*precio_l)*desc_l);
                   this.txttotal.setText(String.valueOf(total_l));
               } 
            }
            
        }
        
    }
    
    public void descuentos_mujeres_mexicanas(){
     Double cantidad_s,precio_s,total_s,desc_s = 0.04;
        Double cantidad_m,precio_m,total_m,desc_m = 0.09;
        Double cantidad_l,precio_l,total_l,desc_l = 0.12;
        
        //Selecciona S
        if(cbonacionalidad.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
               if(cbotallas.getSelectedIndex() == 1){
                   cantidad_s = Double.parseDouble(this.spcantidad.getName());
                   precio_s = Double.parseDouble(this.txtprecio.getText());
                   total_s = (precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                   this.txttotal.setText(String.valueOf(total_s));
               } 
            }
            
        }
        
        //Selecciona M
        if(cbonacionalidad.getSelectedIndex() == 2){
            if(this.botonm.isSelected()){
               if(cbotallas.getSelectedIndex() == 2){
                   cantidad_m = Double.parseDouble(this.spcantidad.getName());
                   precio_m = Double.parseDouble(this.txtprecio.getText());
                   total_m = (precio_m*cantidad_m)-((cantidad_m*precio_m)*desc_m);
                   this.txttotal.setText(String.valueOf(total_m));
               } 
            }
            
        }
        //Selecciona L
        if(cbonacionalidad.getSelectedIndex() == 1){
            if(this.botonm.isSelected()){
               if(cbotallas.getSelectedIndex() == 3){
                   cantidad_l = Double.parseDouble(this.spcantidad.getName());
                   precio_l = Double.parseDouble(this.txtprecio.getText());
                   total_l = (precio_l*cantidad_l)-((cantidad_l*precio_l)*desc_l);
                   this.txttotal.setText(String.valueOf(total_l));
               } 
            }
            
        }        
    } 
    public  void descuentos_hombres_mexicanos(){
        double cantidad_s,precio_s,total_s,desc_s=0.05;
        double cantidad_m,precio_m,total_m,desc_m=0.07;
        double cantidad_l,precio_l,total_l,desc_l=0.10;

        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex()==1){
                    cantidad_s=Double.parseDouble(this.txtcantidad.getText());
                    precio_s=Double.parseDouble(this.txtprecio.getText());
                    total_s=(precio_s*cantidad_s)-((cantidad_s*precio_s)*desc_s);
                    this.txttotal.setText(String.valueOf(total_s));
                }
            }
        }
         if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex()==2){
                    cantidad_m=Double.parseDouble(this.txtcantidad.getText());
                    precio_m=Double.parseDouble(this.txtprecio.getText());
                    total_m=(precio_m*cantidad_m)-((cantidad_m*precio_m*desc_m);
                    this.txttotal.setText(String.valueOf(total_m));
                }
            }
        }
        if(cbonacionalidad.getSelectedIndex()==1){
            if(this.botonh.isSelected()){
                if(cbotallas.getSelectedIndex()==3){
                    cantidad_l=Double.parseDouble(this.txtcantidad.getText());
                    precio_l=Double.parseDouble(this.txtprecio.getText());
                    total_l=(precio_l*cantidad_l)-((cantidad_l*precio_l*desc_l);
                    this.txttotal.setText(String.valueOf(total_l));
                }
            }
        }
        

    }

    private void cbonacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbonacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbonacionalidadActionPerformed

    private void botonhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonhActionPerformed

    private void botonmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonmActionPerformed

    private void btnlimpiartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiartablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlimpiartablaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonh;
    private javax.swing.JRadioButton botonm;
    private javax.swing.JButton btngenerar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnlimpiartabla;
    private javax.swing.JButton btnnetopagar;
    private javax.swing.JButton btnquitar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbonacionalidad;
    private javax.swing.JComboBox<String> cbotallas;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSpinner spcantidad;
    private javax.swing.JTable tabledetalles;
    private javax.swing.JTextField txtnetopagar;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprenda;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
