/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tiendaropa;

/**
 *
 * @author alejandrosuarez
 */
public class Inicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        // Centrar ventana
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnrealizarcompra = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        panelpizarra = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(139, 150, 149));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnrealizarcompra.setText("Realizar Compra");
        btnrealizarcompra.addActionListener(this::btnrealizarcompraActionPerformed);
        jPanel1.add(btnrealizarcompra, new java.awt.GridBagConstraints());

        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 10));
        jPanel1.add(jSeparator1, new java.awt.GridBagConstraints());

        jButton2.setText("Informacion Sobre Tallas");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2, new java.awt.GridBagConstraints());

        panelpizarra.setBackground(new java.awt.Color(255, 255, 255));
        panelpizarra.setPreferredSize(new java.awt.Dimension(0, 600));
        panelpizarra.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
            .addComponent(panelpizarra, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelpizarra, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrealizarcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrealizarcompraActionPerformed
        // Creamos una instancia del panel de compra
        frmRealizarCompra seccionCompra = new frmRealizarCompra();
        
        // Asignamos el tamaño del contenedor
        seccionCompra.setSize(panelpizarra.getWidth(), panelpizarra.getHeight());
        seccionCompra.setLocation(0,0);
    
        // Limpiamos el contenedor por si hay alguna seccion abierta
        panelpizarra.removeAll();
    
        // Agregamos el nuevo panel al centro
        panelpizarra.add(seccionCompra, java.awt.BorderLayout.CENTER);
    
        // Avisamos a Swingg que se actualice la vista
        panelpizarra.revalidate();
        panelpizarra.repaint();
    }//GEN-LAST:event_btnrealizarcompraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Creamos una instancia del panel de informacion
        frmInformacionTallas seccionInformacion = new frmInformacionTallas();
        
        // Asignamos el tamaño del contenedor
        seccionInformacion.setSize(panelpizarra.getWidth(), panelpizarra.getHeight());
        seccionInformacion.setLocation(0,0);
    
        // Limpiamos el contenedor por si hay alguna seccion abierta
        panelpizarra.removeAll();
    
        // Agregamos el nuevo panel al centro
        panelpizarra.add(seccionInformacion, java.awt.BorderLayout.CENTER);
    
        // Avisamos a Swingg que se actualice la vista
        panelpizarra.revalidate();
        panelpizarra.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrealizarcompra;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelpizarra;
    // End of variables declaration//GEN-END:variables
}
